server:
  port: 8084

spring:
  application:
    name: config-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  zipkin:
    base-url: http://localhost:10085
  rabbitmq:
    host: 192.168.24.135
    port: 5672
    username: guest
    password: guest
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  security:
    enable: false
#  main:
#    allow-bean-definition-overriding: true
