server:
  port: 8084

spring:
  application:
    name: config-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
  zipkin:
    base-url: http://localhost:10085
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  security:
    enable: false

refreshtest: admin
#  main:
#    allow-bean-definition-overriding: true
