server:
  port: 8084

spring:
  application:
    name: config-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  zipkin:
    base-url: http://localhost:10085
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  security:
    enable: false

  boot:
    admin:
      url: http://localhost:8083
#  main:
#    allow-bean-definition-overriding: true