server:
  port: 8761

spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  zipkin:
    base-url: http://localhost:10085
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  boot:
    admin:
      client:
        url: http://localhost:8084
